name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger this on pushing to the main branch

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Log in to Docker Hub using GitHub Secrets
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # GitHub Secret for Docker Hub Username
        password: ${{ secrets.DOCKER_PASSWORD }}  # GitHub Secret for Docker Hub Password

    # Build the Docker image and tag it
    - name: Build Docker image
      run: |
        docker build -t kelvyn2012/django-messaging-app:latest -f messaging_app/Dockerfile .

    # Push the Docker image to Docker Hub
    - name: Push Docker image
      run: |
        docker push kelvyn2012/django-messaging-app:latest
