# Generated by Django 5.2.4 on 2025-09-18 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='Conversation_id',
            new_name='conversation_id',
        ),
    ]
